Changes to use D8/R8
~~ csproj ~~

I think these settings make the most sense.

Debug mode:
* AndroidDexTool=d8
* AndroidEnableMultiDex=true

Release mode:
* AndroidDexTool=d8
* AndroidLinkTool=r8

~~ proguard.cfg ~~

I used the rules we are using here:

https://github.com/xamarin/xamarin-android/blob/efb679959bf2ebd1591d5463e5dc26895f43c204/tests/Xamarin.Forms-Performance-Integration/Droid/proguard.cfg

Then also added one rule to avoid:

    java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider:
    java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider"

~~ org.apache.httpclient ~~

This app needs to add:

    <application android:label="Xamarin.Forms.ContributorGallery.Android">
        <uses-library android:name="org.apache.http.legacy" android:required="false" />
    </application>

See: https://github.com/xamarin/xamarin-android/issues/2670#issuecomment-465864421